config/routes.rb
Rails.application.routes.draw do
  

  
  resources :kids do
    resources :candies
  end

 root 'kids#index'

end

app/models/candy.rb
class Candy < ActiveRecord::Base
  belongs_to :kid
end

app/models/kid.rb
class Kid < ActiveRecord::Base
	has_many :candies, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  before_action :set_candy, only: [:show, :edit, :update, :destroy]

  # GET /candies
  # GET /candies.json
  def index
    @candies = Candy.all
    @kid = Kid.find(params[:kid_id])
  end

  # GET /candies/1
  # GET /candies/1.json
  def show
        @kid = Kid.find(params[:kid_id])
  end

  # GET /candies/new
  def new
    @candy = Candy.new
    @kid = Kid.find(params[:kid_id])    
  end

  # GET /candies/1/edit
  def edit
    @kid = Kid.find(params[:kid_id])
  end

  # POST /candies
  # POST /candies.json
  def create
    @candy = Candy.new(candy_params)
     @kid = Kid.find(params[:kid_id])
    respond_to do |format|
      if @candy.save
        format.html { redirect_to kid_candy_path(@kid,@candy), notice: 'Candy was successfully created.' }
        format.json { render :show, status: :created, location: @candy }
      else
        format.html { render :new }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candies/1
  # PATCH/PUT /candies/1.json
  def update
    @kid = Kid.find(params[:kid_id])
    respond_to do |format|
      if @candy.update(candy_params)
        format.html { redirect_to kid_candy_path(@kid,@candy), notice: 'Candy was successfully updated.' }
        format.json { render :show, status: :ok, location: @candy }
      else
        format.html { render :edit }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candies/1
  # DELETE /candies/1.json
  def destroy

    puts "========================================"

    puts params[:kid_id], params[:id]


    puts "========================================"
     @kid = Kid.find(params[:kid_id])
    @candy.destroy
    respond_to do |format|
      format.html { redirect_to kid_path(@kid), notice: 'Candy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candy

      @candy = Candy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candy_params
      params.require(:candy).permit(:name, :kid_id)
    end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params.require(:kid).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candies_helper.rb
module CandiesHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/candies/_form.html.erb
<%= simple_form_for([@kid, @candy]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    
    <%#= f.input :kid_id, :as => :hidden, :input_html => { :value => @kid.id }%>
   <%= f.hidden_field :kid_id, :value => @kid.id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/candies/edit.html.erb
<h1>Editing candy</h1>

<%= render 'form' %>

<%= link_to 'Show', kid_candy_path(@kid,@candy) %> |
<%= link_to 'Back', kid_path(@kid) %>

app/views/candies/index.html.erb
<h1>Listing candies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candies.each do |candy| %>
      <tr>
        <td><%= candy.name %></td>
        <td><%= @kid.name %></td>
        <td><%= link_to 'Show', kid_candy_path(@kid,candy) %></td>
        <td><%= link_to 'Edit', edit_kid_candy_path(@kid,candy) %></td>
        <td><%= link_to 'Destroy', kid_candy_path(@kid,candy), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candy', new_kid_candy_path %>

app/views/candies/new.html.erb
<h1>New candy</h1>

<%= render 'form' %>

<%= link_to 'Back', kid_path(@kid) %>

app/views/candies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candy.name %>
</p>

<p>
  <strong>Kid:</strong>
  <%= @candy.kid.name %>
</p>

<%= link_to 'Edit', edit_kid_candy_path(@kid,@candy) %> |<%= link_to "Delete" ,kid_candy_path(@kid,@candy), method: :delete %>|
<%= link_to 'Back', kid_path(@kid) %>

app/views/kids/_form.html.erb
<%= simple_form_for(@kid) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<h1>Editing kid</h1>

<%= render 'form' %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<h1>Listing kids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.name %></td>
        <td><%= link_to 'Show', kid %></td>
        <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
        <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kid', new_kid_path %>

app/views/kids/new.html.erb
<h1>New kid</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_path %>

app/views/kids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kid.name %>
</p>

<%= link_to 'Edit', edit_kid_path(@kid) %> |
<%= link_to 'Back', kids_path %>

|
<%= link_to " New Candy ", new_kid_candy_path(@kid) %>
<h2>Candies</h2>


<%if @kid.candies.count == 0 %>
  no stock
<% else %>
<ul>

  <% @kid.candies.each do |candy| %>
  	<li><%= link_to candy.name ,kid_candy_path(@kid,candy)%>  	</li>
  
  <% end %>
</ul>

	
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssoProj</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>